
[default]
mode = "debug"
jwt_key = "djhjekagfg244785sdfas2"


[database]
name = "root"
password = "root"
database_type = "mysql"
database_name = "go_web"



[logger]
file_path = "./"
file_name = "gin.log"
